### PR TITLE
Add the option to filter element with more than one key to _doesPassF…

### PR DESCRIPTION
**Pull request by davidgallego**
…ilter the new option is this.options.filterMode and values Shuffle.filterMode.EXCLUSIVE or Shuffle.filterMode.ADDITIVE

### CODE REVIEW

**Comment by davidgallego** [comment]
Sorry for the change at package.json, I'm newbie in pull requests.
The changes I've made are used to filter by more than one key, for this I use the option "filterMode", by default it is "exclusive" and filters only by a key (some), as it worked before, the "additive" option filters all elements that match all keys (every)

**Comment by Vestride** [comment]
Thanks for the contribution! It also made me realize I didn't have ESLint set up with my test script :)

What problem did this change help you solve?

**Comment by davidgallego** [comment]
Hi, thank you for your comment!
This is my use case:
I have a list and several filters that filter that list, with the original script if I selected two filters it showed all the elements that matched **some** of the filters, but what I needed was to show me the elements that **matched both filters**.

Maybe the name I have assigned to the filterMode options is not very correct. Maybe "exclusive" should be "some" and "additive" should be "every".

**Comment by Vestride** [comment]
Published with `v4.2.0`. I changed the filter modes to "any" and "all". Thanks!

**Pull request merged**
